# -*- coding: utf-8 -*-
"""kakao_crawling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KwQkbCgQmfLCbYvaPsvxaYnAl-aaZDZL
"""

import requests
import json

rest_api_key = ""

class KakaoLocalAPI:

  def __init__(self, rest_api_key):

    self.rest_api_key = rest_api_key
    self.headers = {'Authorization': 'KakaoAK {}'.format(rest_api_key)}
    self.search_address_url = "https://dapi.kakao.com/v2/local/geo/coord2address.json"
    self.search_category_url = "https://dapi.kakao.com/v2/local/search/category.json"
    self.search_region_url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
    
  def search_address(self, x, y):
        
    params = {"x": f"{x}",
              "y": f"{y}"}
     
    res = requests.get(self.search_address_url, headers=self.headers, params=params)
    document = json.loads(res.text) 
    match_first = document['documents'][0]['address']['address_name']
    return match_first
      
  def search_category(self, x, y):    

    params = {'category_group_code': "SW8",
              'x': f"{x}",
              'y': f"{y}",
              'radius': "2000"}

    res = requests.get(self.search_category_url, headers=self.headers, params=params)
    document = json.loads(res.text)
    # return document
    match_first = document['documents'][0]
    return match_first['place_name'], int(match_first['distance'])

  def search_region(self, x, y):   
        
    params = {"x": f"{x}",
              "y": f"{y}"}
        
    res = requests.get(self.search_region_url, headers=self.headers, params=params)
    document = json.loads(res.text)
    match_first = document['documents'][0]['region_3depth_name']
    return match_first

kakao = KakaoLocalAPI(rest_api_key)

address = "서울특별시 도봉구 방학동 396-22"

test1 = kakao.search_address(address)
test1

test2 = kakao.search_near_subway(test1[0], test1[1])
test2

